## Importing libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('IRIS.csv')

In [3]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Data Preprocessing

In [4]:
data.shape

(150, 5)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
data['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [8]:
x = data.drop(columns = 'species',axis = 1)
y = data['species']

In [9]:
print(x)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [10]:
print(y)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object


## Label Encoding

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()

In [13]:
Y = le.fit_transform(y)

In [14]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Spliting of Data

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,Y_train,Y_test = train_test_split(x,Y,test_size = 0.2,random_state=1,stratify=Y)

In [17]:
x_train.shape

(120, 4)

In [18]:
x_train

sepal_length  sepal_width  petal_length  petal_width
21            5.1          3.7           1.5          0.4
47            4.6          3.2           1.4          0.2
141           6.9          3.1           5.1          2.3
90            5.5          2.6           4.4          1.2
64            5.6          2.9           3.6          1.3
..            ...          ...           ...          ...
41            4.5          2.3           1.3          0.3
93            5.0          2.3           3.3          1.0
26            5.0          3.4           1.6          0.4
3             4.6          3.1           1.5          0.2
42            4.4          3.2           1.3          0.2

[120 rows x 4 columns]

In [19]:
x_test.shape

(30, 4)

In [20]:
Y_train

array([0, 0, 2, 1, 1, 1, 1, 2, 2, 1, 2, 0, 1, 1, 2, 0, 2, 1, 1, 0, 0, 2,
       2, 1, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 2, 2,
       1, 1, 2, 1, 1, 0, 2, 0, 2, 0, 0, 1, 0, 1, 2, 0, 2, 0, 0, 2, 2, 0,
       1, 0, 0, 1, 2, 1, 1, 0, 0, 1, 2, 1, 1, 2, 1, 2, 0, 1, 2, 1, 1, 0,
       0, 2, 1, 2, 1, 0, 1, 2, 2, 0, 0, 2, 2, 0, 2, 1, 1, 1, 2, 0, 2, 1,
       2, 0, 2, 0, 1, 0, 1, 0, 0, 0])

In [21]:
Y_test

array([2, 0, 1, 0, 0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 2, 1, 1,
       0, 0, 2, 2, 0, 0, 1, 1])

## Builiding Classification Model

### Logistic Regression classifier

In [22]:
from  sklearn.linear_model import LogisticRegression

In [23]:
model = LogisticRegression()

In [24]:
model.fit(x_train,Y_train)

C:\Users\lohch\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
predict_x_train = model.predict(x_train)

## Checking accuracy of Model

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
accuracy_train = accuracy_score(predict_x_train,Y_train) * 100

In [28]:
accuracy_train

96.66666666666667

In [29]:
predict_x_test = model.predict(x_test)

In [33]:
accuracy_test = accuracy_score(predict_x_test,Y_test) * 100

In [34]:
accuracy_test

96.66666666666667

## Evaluating Model Performance

In [35]:
array = [5.1,3.5,1.4,0.2]
array_np = np.asarray(array)
array_rs = array_np.reshape(1,-1)
prediction = model.predict(array_rs)
prediction
if prediction[0]== 0:
    print('Iris-setosa')
elif prediction[0]== 1:
    print('Iris-versicolor')
else:
    print('Iris-virginica ')

Iris-setosa


C:\Users\lohch\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
